version: '2'
services:

  web:
    # image: mustang-news-service:1.0
    image: node:6.4.0
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm install -g nodemon; nodemon -e js, .'
    ports:
      - "9000:9000"
      - "9229:9229"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      MASTER_KEY: "VIrPcAi4Rff0gBwdWklRl3ywMwgC6mZH"
      JWT_SECRET: "BOeX5ECZhiEsy8NSmAgJZ55eVcwQYnMy"

  mongo:
    image: mongo:3.4
    ports:
      - '27017:27017'
    networks:
      - all

networks:
  all:
